# Generated by Django 5.1.3 on 2024-11-14 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField()),
                ('productDate', models.DateField(auto_now_add=True)),
                ('productImage', models.ImageField(upload_to='images/')),
                ('productAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProduct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
